# Generated by Django 5.2.5 on 2025-08-21 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('full_emr', '0004_appointment_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpatients',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
