# Generated by Django 5.2.5 on 2025-08-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('full_emr', '0005_alter_addpatients_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpatients',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
