# Generated by Django 5.2.5 on 2025-08-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('full_emr', '0007_diagnostic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
