# Generated by Django 5.2.5 on 2025-09-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('full_emr', '0009_labreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('pharmacy', 'Pharmacist'), ('patient', 'patient')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='speciality',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
