# Generated by Django 5.2.5 on 2025-09-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('full_emr', '0010_alter_user_role_alter_user_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('reviewed', 'Reviewed')], default='pending', max_length=20),
        ),
    ]
