# Generated by Django 5.2.5 on 2025-09-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('full_emr', '0012_allergy_familyhistory_immunization_medicalhistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsigns',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
