# Generated by Django 5.2.5 on 2025-09-16 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('full_emr', '0018_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'ordering': ['-created_at']},
        ),
    ]
